package org.jokar.permissiondispatcher.processor.event;

import com.squareup.javapoet.ClassName;

/**
 * Created by JokAr on 16/8/23.
 */
public interface ConstantsProvider {

    ClassName ACTIVITY_COMPAT = ClassName.get("android.support.v4.app", "ActivityCompat");
    ClassName PERMISSION_UTILS = ClassName.get("permissions.dispatcher", "PermissionUtils");
    String ACTIVITY = "android.app.Activity";
    String V4FRAGMENT = "android.support.v4.app.Fragment";
    String CLASS_SUFFIX = "PermissionsDispatcher";
    String METHOD_SUFFIX = "WithCheck";
    String REQUEST_CODE_PREFIX = "REQUEST_";
    String PERMISSION_PREFIX = "PERMISSION_";
    String GEN_PENDING_PREFIX = "PENDING_";
    String FILE_COMMENT = "This file was generated by PermissionsDispatcher. Do not modify!";
    String GEN_CLASS_SUFFIX = "PermissionsDispatcher";
}
